### ISSUE TITLE
Error using xfeat+lighterglue

### ISSUE THREAD

**Issue by ichsan2895** [pablovela5620/hloc-glomap#6]
Seems a bug when I set the matcher to `xfeat+lighterglue` ?

```
>> python3 tools/reconstruct.py --image-dir "/workspace/DATASET/images_4_Terrestial" --verbose --mapper-cmd glomap --feature-type xfeat --matcher-type xfeat+lighterglue

[2024/12/24 17:15:23 hloc INFO] Matching local features with configuration:
{'model': {'features': 'xfeat', 'name': 'lighterglue'},
 'output': 'matches-xfeat-lighterglue'}
Traceback (most recent call last):
  File "/hloc-glomap/tools/reconstruct.py", line 91, in <module>
    main(
  File "/hloc-glomap/tools/reconstruct.py", line 72, in main
    run_hloc_reconstruction(
  File "/hloc-glomap/hloc_glomap/process_data.py", line 298, in run_hloc_reconstruction
    match_features.main(
  File "/hloc-glomap/.pixi/envs/default/lib/python3.11/site-packages/hloc/match_features.py", line 188, in main
    match_from_paths(conf, pairs, matches, features_q, features_ref, overwrite)
  File "/hloc-glomap/.pixi/envs/default/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/hloc-glomap/.pixi/envs/default/lib/python3.11/site-packages/hloc/match_features.py", line 245, in match_from_paths
    model = Model(conf["model"]).eval().to(device)
            ^^^^^^^^^^^^^^^^^^^^
  File "/hloc-glomap/.pixi/envs/default/lib/python3.11/site-packages/hloc/utils/base_model.py", line 18, in __init__
    self._init(conf)
  File "/hloc-glomap/.pixi/envs/default/lib/python3.11/site-packages/hloc/matchers/lighterglue.py", line 35, in _init
    self.net = LightGlue_(None, **conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LightGlue.__init__() got multiple values for argument 'features'
```

Additional info:
Ubuntu 22.04.3 LTS
hloc-glomap commit a907f6480efccd4d16609074d6a00140253bbdb0

**Comment by pablovela5620** [comment]
hmm, I'll do some debugging after the holidays and get back to you
